FROM arm32v7/python:slim

WORKDIR /home/pi/temp

RUN apt-get update && apt-get install --no-install-recommends -y python3-pip && apt-get clean

RUN pip3 install smbus2

COPY . .

CMD [ "python3", "./main.py" ]
